### ISSUE TITLE
Just A Question and a Thank you

### ISSUE THREAD

**Issue by megphillips91** [MarkMarzeotti/gutenberg-repeater-field#4]
Ever have one of those days when you know you should go take a run and instead you push your forehead closer to the keys spinning around the same thing you already know you know? Yesterday....anyway thanks for bringing me back down to the simplicity of this. I think we all stumble over the "why". That is my issue. I am not sure I need a repeater in my use case, but I've been asked to make it a repeater - so that is what I will do - and very happily. Work is good. No work is bad. 

As to the issue - simple question - why square brackets on the return? Is there a significance there I am missing or is it just no matter?

Thanks again, 
Meg Phillips 91

**Comment by MarkMarzeotti** [comment]
Hey Meg,

I hear ya. When I was first asked about this my reply was why? In a Gutenberg environment why not just use multiple blocks? but when building out a Google maps block it turned out to be the best way to keep track of multiple locations and an example where multiple blocks would not solve the problem. I understand just pleasing the client at the end of the day and I hope this repo helps you do that. Just saying this as for the record, I don't think this is the best way to solve something repeating in a layout. But heres how to do it if you have an option that has multiple sub items contained in a single block (like a map that needs to show infinite points). The biggest piece being a map block cannot have child blocks. But thats all there. Hope this solves a problem for you.

As for the square brackets, if you are referring to line 106 in `/src/block/block.js`...

```
		return [
			<InspectorControls key="1">
				<PanelBody title={ __( 'Locations' ) }>
					{ locationFields }
					<Button
						isDefault
						onClick={ handleAddLocation.bind( this ) }
					>
						{ __( 'Add Location' ) }
					</Button>
				</PanelBody>
			</InspectorControls>,
			<div key="2" className={ props.className }>
				<h2>Block</h2>
				{ locationDisplay }
			</div>,
		];
```

The brackets are because I am returning two components, InspectorControls and the div that is my block. You'll see on line 117 that there is a comma. The square brackets are because I am returning an array. The first item is the `<InspectorControls>` component and the second being the div. Another option would have been to wrap both elements in a `<Fragment>` component. React returns using parenthesis expect exactly one component, but you can return multiple if you return an array (as long as they are keyed).
